version: 1
git_protocol: https
editor:
prompt: enabled
prefer_editor_prompt: enabled
pager:
aliases:
    co: pr checkout
http_unix_socket:
browser:
color_labels: enabled
accessible_colors: disabled
accessible_prompter: disabled
spinner: enabled
