[packageManagers.brew]

root = false
command = "install"
args = [
  "--force",
]

[packageManagers.brew.darwin]

taps = [
  "oven-sh/bun",
  "waydabber/betterdisplay",
]

brews = [
  "age",
  "aria2",
  "bat",
  "waydabber/betterdisplay/betterdisplaycli",
  "bottom",
  "oven-sh/bun/bun",
  "chezmoi",
  "codesnap",
  "coreutils",
  "exiftool",
  "eza",
  "fastfetch",
  "fish",
  "fisher",
  "fd",
  "ffmpeg",
  "fzf",
  "gh",
  "git",
  "git-delta",
  "git-lfs",
  "imagemagick",
  "iperf3",
  "jq",
  "lazygit",
  "lefthook",
  "librsvg",
  "mermaid-cli",
  "neovim",
  "node",
  "opencode",
  "openjdk",
  "openssh",
  "pandoc",
  "poppler",
  "posting",
  "p7zip",
  "rclone",
  "resvg",
  "ripgrep",
  "rust",
  "uv",
  "yazi",
  "zoxide",
]

casks = [
  "aldente",
  "bartender",
  # "basictex",
  "betterdisplay",
  "bettertouchtool",
  "chatgpt",
  "cleanmymac",
  "downie",
  "font-symbols-only-nerd-font",
  "font-sf-compact",
  "font-sf-mono",
  "font-sf-pro",
  "ghostty",
  "google-chrome",
  "notchnook",
  "notion",
  "orbstack",
  "stats",
  "surge",
  "tailscale-app",
]

[[packageManagers.brew.darwin.mas]]
name = "Compressor"
id = 6746516157

[[packageManagers.brew.darwin.mas]]
name = "Developer"
id = 640199958

[[packageManagers.brew.darwin.mas]]
name = "Final Cut Pro"
id = 1631624924

[[packageManagers.brew.darwin.mas]]
name = "Keynote"
id = 361285480

[[packageManagers.brew.darwin.mas]]
name = "Logic Pro"
id = 1615087040

[[packageManagers.brew.darwin.mas]]
name = "MainStage"
id = 6746637089

[[packageManagers.brew.darwin.mas]]
name = "Motion"
id = 6746637149

[[packageManagers.brew.darwin.mas]]
name = "Numbers"
id = 361304891

[[packageManagers.brew.darwin.mas]]
name = "Pages"
id = 361309726

[[packageManagers.brew.darwin.mas]]
name = "Pixelmator Pro"
id = 6746662575

[[packageManagers.brew.darwin.mas]]
name = "TestFlight"
id = 899247664

[[packageManagers.brew.darwin.mas]]
name = "Transporter"
id = 1450874784

[[packageManagers.brew.darwin.mas]]
name = "Xcode"
id = 497799835

[[packageManagers.brew.darwin.mas]]
name = "Immersive Translate"
id = 6447957425

[[packageManagers.brew.darwin.mas]]
name = "Infuse"
id = 1136220934

[[packageManagers.brew.darwin.mas]]
name = "Magnet"
id = 441258766

[[packageManagers.brew.darwin.mas]]
name = "Noir"
id = 1592917505

[[packageManagers.brew.darwin.mas]]
name = "Tampermonkey"
id = 6738342400

[packageManagers.brew.linux]

taps = [
  "oven-sh/bun",
]

brews = [
  "age",
  "aria2",
  "bat",
  "bottom",
  "oven-sh/bun/bun",
  "caddy",
  "chezmoi",
  "eza",
  "fastfetch",
  "ffmpeg",
  "fish",
  "fisher",
  "fd",
  "fzf",
  "gh",
  "git",
  "git-delta",
  "git-lfs",
  "imagemagick",
  "iperf3",
  "jq",
  "neovim",
  "opencode",
  "p7zip",
  "poppler",
  "resvg",
  "ripgrep",
  "sing-box",
  "tailscale",
  "tldr",
  "tree-sitter-cli",
  "yazi",
  "zoxide",
]

casks = [
  "font-fira-mono-nerd-font",
  "font-inter",
  "font-sarasa-gothic",
]

[packageManagers.brew.minimal]

[packageManagers.brew.minimal.darwin]
taps = [
  "oven-sh/bun",
]

brews = [
  "age",
  "bat",
  "bottom",
  "oven-sh/bun/bun",
  "chezmoi",
  "coreutils",
  "eza",
  "fastfetch",
  "fish",
  "fisher",
  "fd",
  "fzf",
  "git",
  "git-delta",
  "git-lfs",
  "neovim",
  "p7zip",
  "ripgrep",
  "tldr",
  "yazi",
  "zoxide",
]

casks = [
  "bartender",
  "betterdisplay",
  "bettertouchtool",
  "chatgpt",
  "cleanmymac",
  "font-sf-compact",
  "font-sf-mono",
  "font-sf-pro",
  "ghostty",
  "google-chrome",
  "notchnook",
  "notion",
  "orbstack",
  "stats",
  "surge",
  "tailscale-app",
]

[[packageManagers.brew.minimal.darwin.mas]]
name = "TestFlight"
id = 899247664

[packageManagers.brew.minimal.linux]
taps = [
  "oven-sh/bun"
]

brews = [
  "age",
  "bat",
  "bottom",
  "oven-sh/bun/bun",
  "chezmoi",
  "eza",
  "fastfetch",
  "fish",
  "fisher",
  "fd",
  "fzf",
  "gh",
  "git",
  "git-delta",
  "git-lfs",
  "neovim",
  "p7zip",
  "ripgrep",
  "tldr",
  "yazi",
  "zoxide",
]

casks = []
