[packageManagers.pacman]

root = true
command = ""
args = [
  "-S",
  "--needed",
  "--noconfirm",
]

drivers = [
  "acpi",
  "cuda",
  "nvidia-open",
  "nvidia-utils",
]

packages = [
  "age",
  "aria2",
  "bat",
  "bottom",
  "bun",
  "caddy",
  "chezmoi",
  "exiftool",
  "eza",
  "fastfetch",
  "fish",
  "fisher",
  "fd",
  "fzf",
  "git",
  "git-delta",
  "github-cli",
  "git-lfs",
  "imagemagick",
  "iperf3",
  "jq",
  "librsvg",
  "neovim",
  "podman",
  "poppler",
  "p7zip",
  "ripgrep",
  "tailscale",
  "tldr",
  "tree-sitter",
  "wayvnc",
  "wl-clipboard",
  "yazi",
  "zoxide",
  "ghostty",
  "otf-firamono-nerd",
  "ttf-sarasa-gothic",
  "inter-font",
]

[packageManagers.pacman.minimal]

packages = [
  "age",
  "bat",
  "bottom",
  "bun",
  "chezmoi",
  "eza",
  "fastfetch",
  "fish",
  "fisher",
  "fd",
  "fzf",
  "git",
  "git-delta",
  "github-cli",
  "git-lfs",
  "neovim",
  "podman",
  "p7zip",
  "ripgrep",
  "tldr",
  "yazi",
  "zoxide",
]

[packageManagers.paru]

root = false
command = ""
args = [
  "-S",
  "--needed",
  "--noconfirm",
  "--skipreview",
]

drivers = [
  "ncurses5-compat-libs",
]

packages = [
  "opencode-bin",
  "go-gitmoji-cli-bin",
  "rustdesk",
  "sing-box",
  "google-chrome",
]

[packageManagers.paru.minimal]

packages = [
  "go-gitmoji-cli-bin",
]
