[snippets]
custom_paths = []
include_default_snippets = true

[experimental]
server_side_pdf_export = true

[keymap]
preset = "vim"

[keymap.overrides]

[package_management]
manager = "uv"

[language_servers.ty]
enabled = false

[language_servers.basedpyright]
enabled = false

[language_servers.pylsp]
enable_ruff = true
enabled = true
enable_pydocstyle = false
enable_pyflakes = false
enable_flake8 = false
enable_pylint = false
enable_mypy = true

[ai]
inline_tooltip = true

[ai.custom_providers]

[ai.models]
custom_models = []
chat_model = "openai/gpt-5"
edit_model = "openai/gpt-5"
displayed_models = []

[display]
dataframes = "rich"
default_table_max_columns = 50
cell_output = "below"
reference_highlighting = true
default_width = "compact"
theme = "system"
default_table_page_size = 10
code_editor_font_size = 14

[formatting]
line_length = 79

[completion]
activate_on_typing = true
copilot = "github"
signature_hint_on_typing = true

[mcp]
presets = []

[mcp.mcpServers]

[runtime]
output_max_bytes = 8000000
watcher_on_save = "lazy"
on_cell_change = "autorun"
auto_reload = "autorun"
default_sql_output = "auto"
std_stream_max_bytes = 1000000
auto_instantiate = true
reactive_tests = true
default_csv_encoding = "utf-8"

[save]
autosave = "after_delay"
format_on_save = true
autosave_delay = 1000

[diagnostics]
sql_linter = true
enabled = false

[server]
browser = "default"
follow_symlink = false
