[devices]

[devices.aws-ec2]
os = "arch"
minimal = true

[devices.laptop]
os = "arch"
minimal = false

[devices.mac-mini]
os = "darwin"
minimal = true

[devices.macbook-air]
os = "darwin"
minimal = false

[devices.minisforum]
os = "nixos"
minimal = false

[devices.raspberrypi]
os = "debian"
minimal = true

# Virtual Machines
[devices.arch]
os = "arch"
minimal = true
