[flatpak]

[[flatpak.remotes]]
name = "flathub"
location = "https://dl.flathub.org/repo/flathub.flatpakrepo"
apps = [
  "com.github.tchx84.Flatseal",
  "com.google.Chrome",
  "com.valvesoftware.Steam",
]
