[homebrew]

[homebrew.darwin]
taps = [
  "oven-sh/bun",
  "waydabber/betterdisplay",
]

brews = [
  "bat",
  "waydabber/betterdisplay/betterdisplaycli",
  "bottom",
  "oven-sh/bun/bun",
  "chezmoi",
  "codesnap",
  "coreutils",
  "fastfetch",
  "fish",
  "fisher",
  "fd",
  "ffmpeg",
  "fzf",
  "gh",
  "git",
  "git-delta",
  "git-lfs",
  "imagemagick",
  "iperf3",
  "lazygit",
  "lefthook",
  "mermaid-cli",
  "neovim",
  "node",
  "openjdk",
  "openssh",
  "pandoc",
  "posting",
  "p7zip",
  "rclone",
  "ripgrep",
  "rust",
  "uv",
  "yazi",
  "zoxide",
]

casks = [
  "aldente",
  "bartender",
  "betterdisplay",
  "bettertouchtool",
  "chatgpt",
  "cleanmymac",
  "codex",
  "downie",
  "font-sf-compact",
  "font-sf-mono",
  "font-sf-pro",
  "ghostty",
  # "mactex-no-gui",
  # "motrix",
  "notchnook",
  "notion",
  "orbstack",
  "stats",
  "surge",
  "tailscale-app",
]

[[homebrew.darwin.mas]]
name = "Developer"
id = 640199958

[[homebrew.darwin.mas]]
name = "Immersive Translate"
id = 6447957425

[[homebrew.darwin.mas]]
name = "Infuse"
id = 1136220934

[[homebrew.darwin.mas]]
name = "Keynote"
id = 409183694

[[homebrew.darwin.mas]]
name = "Magnet"
id = 441258766

[[homebrew.darwin.mas]]
name = "Noir"
id = 1592917505

[[homebrew.darwin.mas]]
name = "Numbers"
id = 409203825

[[homebrew.darwin.mas]]
name = "Pages"
id = 409201541

[[homebrew.darwin.mas]]
name = "Tampermonkey"
id = 6738342400

[[homebrew.darwin.mas]]
name = "TestFlight"
id = 899247664

[[homebrew.darwin.mas]]
name = "Transporter"
id = 1450874784

[[homebrew.darwin.mas]]
name = "Xcode"
id = 497799835

# Microsoft
[[homebrew.darwin.mas]]
name = "Windows App"
id = 1295203466

[[homebrew.darwin.mas]]
name = "Microsoft Word"
id = 462054704

[[homebrew.darwin.mas]]
name = "Microsoft Excel"
id = 462058435

[[homebrew.darwin.mas]]
name = "Microsoft PowerPoint"
id = 462062816


[homebrew.linux]
taps = [
  "oven-sh/bun",
]

brews = [
  "bat",
  "bottom",
  "oven-sh/bun/bun",
  "caddy",
  "chezmoi",
  "fastfetch",
  "fish",
  "fisher",
  "fd",
  "fzf",
  "gh",
  "git",
  "git-delta",
  "git-lfs",
  "imagemagick",
  "iperf3",
  "llvm",
  "mihomo",
  "neovim",
  "p7zip",
  "ripgrep",
  "tailscale",
  "tree-sitter",
  "tldr",
  "yazi",
  "zoxide",
]

casks = [
  "font-fira-mono-nerd-font",
  "font-inter",
  "font-sarasa-gothic",
]
