[minimal]

[minimal.homebrew.darwin]
taps = [
  "oven-sh/bun",
]

brews = [
  "age",
  "bat",
  "bottom",
  "oven-sh/bun/bun",
  "chezmoi",
  "coreutils",
  "fastfetch",
  "fish",
  "fisher",
  "fd",
  "fzf",
  "git",
  "git-delta",
  "github-cli",
  "git-lfs",
  "neovim",
  "p7zip",
  "ripgrep",
  "tldr",
  "yazi",
  "zoxide",
]

casks = [
  "bartender",
  "betterdisplay",
  "bettertouchtool",
  "chatgpt",
  "cleanmymac",
  "font-sf-compact",
  "font-sf-mono",
  "font-sf-pro",
  "ghostty",
  "google-chrome",
  "notchnook",
  "notion",
  "orbstack",
  "stats",
  "surge",
  "tailscale-app",
]

[[minimal.homebrew.darwin.mas]]
name = "TestFlight"
id = 899247664

[minimal.homebrew.linux]
taps = [
  "oven-sh/bun"
]

brews = [
  "age",
  "bat",
  "bottom",
  "oven-sh/bun/bun",
  "chezmoi",
  "fastfetch",
  "fish",
  "fisher",
  "fd",
  "fzf",
  "gh",
  "git",
  "git-delta",
  "git-lfs",
  "neovim",
  "p7zip",
  "ripgrep",
  "tldr",
  "yazi",
  "zoxide",
]

casks = []

[minimal.pacman]

packages = [
  "age",
  "bat",
  "bottom",
  "bun",
  "chezmoi",
  "fastfetch",
  "fish",
  "fisher",
  "fd",
  "fzf",
  "git",
  "git-delta",
  "github-cli",
  "git-lfs",
  "neovim",
  "podman",
  "p7zip",
  "ripgrep",
  "tldr",
  "yazi",
  "zoxide",
]

[minimal.paru]

packages = [
  "gitmoji"
]
