[pacman]

drivers = [
  "nvidia-open",
  "nvidia-utils",
]

packages = [
  "age",
  "bat",
  "bottom",
  "bun",
  "caddy",
  "chezmoi",
  "fastfetch",
  "fish",
  "fisher",
  "fd",
  "fzf",
  "git",
  "git-delta",
  "github-cli",
  "git-lfs",
  "imagemagick",
  "iperf3",
  "jq",
  "neovim",
  "podman",
  "poppler",
  "p7zip",
  "resvg",
  "ripgrep",
  "tailscale",
  "tldr",
  "tree-sitter",
  "yazi",
  "zoxide",
]

applications = [
  "ghostty",
  "gnome",
  "gnome-browser-connector",
  "gnome-tweaks",
  "seahorse",
  "steam",
  "otf-firamono-nerd",
  "ttf-sarasa-gothic",
  "inter-font",
]

[paru]

packages = [
  "mihomo",
  "opencode",
  "gitmoji"
]

applications = [
  "google-chrome",
]
