services:
  namenode:
    image: apache/hadoop:3.4.1
    container_name: namenode
    restart: unless-stopped
    hostname: namenode
    user: root
    command: ["/bin/bash", "/init-namenode.sh"]
    ports:
      - 9870:9870
    environment:
      - HADOOP_HOME=/opt/hadoop
    volumes:
      - ./data/namenode:/opt/hadoop/data/nameNode
      - ./config:/opt/hadoop/etc/hadoop
      - ./init-namenode.sh:/init-namenode.sh
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - hdfs_network

  datanode-1:
    image: apache/hadoop:3.4.1
    container_name: datanode-1
    hostname: datanode-1
    restart: unless-stopped
    user: root
    environment:
      - HADOOP_HOME=/opt/hadoop
    volumes:
      - ./data/datanode-1:/opt/hadoop/data/dataNode
      - ./config:/opt/hadoop/etc/hadoop
      - ./init-datanode.sh:/init-datanode.sh
    depends_on:
      - namenode
    command: ["/bin/bash", "/init-datanode.sh"]
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - hdfs_network

  datanode-2:
    image: apache/hadoop:3.4.1
    container_name: datanode-2
    hostname: datanode-2
    restart: unless-stopped
    user: root
    environment:
      - HADOOP_HOME=/opt/hadoop
    volumes:
      - ./data/datanode-2:/opt/hadoop/data/dataNode
      - ./config:/opt/hadoop/etc/hadoop
      - ./init-datanode.sh:/init-datanode.sh
    depends_on:
      - namenode
    command: ["/bin/bash", "/init-datanode.sh"]
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - hdfs_network

  datanode-3:
    image: apache/hadoop:3.4.1
    container_name: datanode-3
    hostname: datanode-3
    restart: unless-stopped
    user: root
    environment:
      - HADOOP_HOME=/opt/hadoop
    volumes:
      - ./data/datanode-3:/opt/hadoop/data/dataNode
      - ./config:/opt/hadoop/etc/hadoop
      - ./init-datanode.sh:/init-datanode.sh
    depends_on:
      - namenode
    command: ["/bin/bash", "/init-datanode.sh"]
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - hdfs_network

  resourcemanager:
    image: apache/hadoop:3.4.1
    container_name: resourcemanager
    hostname: resourcemanager
    user: root
    restart: unless-stopped
    command: ["yarn", "resourcemanager"]
    ports:
      - 8088:8088
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - hdfs_network

networks:
  hdfs_network:
    driver: bridge
