[".config/mihomo/geoip.dat"]
  type = "file"
  url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat"

[".config/mihomo/geosite.dat"]
  type = "file"
  url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"

[".config/xray/geoip.dat"]
  type = "file"
  url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat"

[".config/xray/geosite.dat"]
  type = "file"
  url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"
