[devicesInfo.fedora]
os = "fedora"
hostname = "fedora"
prettyHostname = "Fedora"

[[devicesInfo.fedora.package]]
manager = "dnf"
minimal = true
[[devicesInfo.fedora.package]]
manager = "brew"
minimal = true

