[devicesInfo.laptop]
os = "arch"
hostname = "laptop"
prettyHostname = "Laptop"

[[devicesInfo.laptop.package]]
manager = "pacman"
minimal = false
[[devicesInfo.laptop.package]]
manager = "paru"
minimal = false
