[devicesInfo.raspberrypi]
os = "debian"
hostname = "raspberrypi"
prettyHostname = "Raspberry Pi"

[[devicesInfo.raspberrypi.package]]
manager = "apt"
minimal = true
[[devicesInfo.raspberrypi.package]]
manager = "brew"
minimal = true
