[gnome]

applications = [
  "gnome-browser-connector",
  "gnome-extensions-app",
  "gnome-tweaks",
  "seahorse",
]

wallpapers = [
  "AnimeRoomBoard",
  "CatherineRoom",
  "ChromeOSBlues",
  "ChromeOSEarth",
  "ChromeOSGreens",
  "ChromeOSReds",
  "ChromeOSWind",
  "ChromeOSYellows",
  "Coast",
  "EOS-Sunset",
  "ExternalHimitsuHouse",
  "FedeMarinMountain",
  "Firewatch",
  "Firewatch2",
  "Fluent",
  "HimitsuHouse",
  "LofiCity",
  "MagicLake",
  "Monterey",
  "Ocean",
  "Riverside",
  "SolidMountain",
  "Solitude",
  "TokyoStreet",
  "Windows-11-3",
  "Wiravketto",
]

extensions = [
  "blur-my-shell@aunetx",
  "compiz-alike-magic-lamp-effect@hermes83.github.com",
  "dash-to-dock@micxgx.gmail.com",
  "dash2dock-lite@icedman.github.com",
  "kiwi@kemma",
  "kiwimenu@kemma",
  "nightthemeswitcher@romainvigier.fr",
  "search-light@icedman.github.com",
  "user-theme@gnome-shell-extensions.gcampax.github.com",
  "Vitals@CoreCoding.com",
]

[[gnome.themes]]
name = "Orchis"
url = "https://github.com/vinceliuice/Orchis-theme"
command = "./install.sh --dest ~/.local/share/themes --icon arch --tweaks macos --tweaks dock --round 4px"

[[gnome.icons]]
name = "Colloid"
url = "https://github.com/vinceliuice/Colloid-icon-theme"
command = "./install.sh --dest $HOME/.local/share/icons"

[[gnome.icons]]
name = "Bibata Modern Ice"
url = "https://github.com/ful1e5/Bibata_Cursor/releases/latest/download/Bibata-Modern-Ice.tar.xz"
